name: lapor_book
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  intl: ^0.19.0
  url_launcher: ^6.2.2
  geolocator: ^10.1.0

  # firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.5.5
  cupertino_icons: ^1.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets: ['assets/', ]


